import { Roboto } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import SideMenu from "@/components/Sidebar";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "GoLedgerfy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StoreProvider>
          <div className="flex column-2">
            <SideMenu />
            <main className="flex-1 p-4 overflow-hidden ">{children}</main>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
